service: aws-experiments-sqs-sns

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    SQS_URL:
      Ref: SQSQueue

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: aws-experiments-sqs-sns-queue

functions:
  usersSubmit:
    handler: handler.usersSubmit
    events:
      - http:
          path: users
          method: post
  usersInvite:
    handler: handler.usersInvite
    events:
      - sqs:
          batchSize: 2
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn




