service: aws-experiments-sqs-sns

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    SQS_URL:
      Ref: SQSQueue
    SNS_ARN:
      Ref: SNSTopic
  iamRoleStatements:
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - Fn::GetAtt: [ SQSQueue, Arn ]
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: SNSTopic


resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: aws-experiments-sqs-sns-queue
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: my-js-sqs-sns-topic  # will be created??
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: aliaksandr_varachai@epam.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic

functions:
  usersSubmit:
    handler: handler.usersSubmit
    events:
      - http:
          path: users
          method: post
  usersInvite:
    handler: handler.usersInvite
    events:
      - sqs:
          batchSize: 2
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn




